#!/usr/bin/env bash
# QraftBox Installer / Uninstaller
#
# Install:
#   curl -fsSL https://raw.githubusercontent.com/tacogips/QraftBox/main/install.sh | bash
#
# Uninstall:
#   curl -fsSL https://raw.githubusercontent.com/tacogips/QraftBox/main/install.sh | bash -s -- --uninstall
#   # or, if qraftbox is installed:
#   qraftbox --uninstall  (not yet; use the curl method)
#
# Options:
#   --npm          Install via npm (requires/installs Bun) instead of binary download
#   --install-dir  Directory to install binary (default: ~/.local/bin)
#   --version      Specific version to install (default: latest)
#   --uninstall    Remove QraftBox and all installed files
#
# Environment Variables:
#   QRAFTBOX_INSTALL_DIR  Same as --install-dir

set -euo pipefail

# ----- Constants -----

REPO="tacogips/QraftBox"
BINARY_NAME="qraftbox"
DEFAULT_INSTALL_DIR="${QRAFTBOX_INSTALL_DIR:-${HOME}/.local/bin}"
RECEIPT_DIR="${HOME}/.config/qraftbox"
RECEIPT_FILE="${RECEIPT_DIR}/.install-receipt"

# ----- Color helpers (disabled if not a terminal) -----

if [ -t 1 ]; then
  BOLD="\033[1m"
  DIM="\033[2m"
  RED="\033[31m"
  GREEN="\033[32m"
  YELLOW="\033[33m"
  CYAN="\033[36m"
  RESET="\033[0m"
else
  BOLD="" DIM="" RED="" GREEN="" YELLOW="" CYAN="" RESET=""
fi

info()  { printf "${CYAN}[info]${RESET}  %s\n" "$*"; }
ok()    { printf "${GREEN}[ok]${RESET}    %s\n" "$*"; }
warn()  { printf "${YELLOW}[warn]${RESET}  %s\n" "$*"; }
error() { printf "${RED}[error]${RESET} %s\n" "$*" >&2; }
die()   { error "$@"; exit 1; }

# ----- Argument parsing -----

INSTALL_METHOD="binary"
INSTALL_DIR="${DEFAULT_INSTALL_DIR}"
VERSION=""
DO_UNINSTALL=false

while [ $# -gt 0 ]; do
  case "$1" in
    --npm)          INSTALL_METHOD="npm"; shift ;;
    --install-dir)  INSTALL_DIR="$2"; shift 2 ;;
    --version)      VERSION="$2"; shift 2 ;;
    --uninstall)    DO_UNINSTALL=true; shift ;;
    --help|-h)
      echo "Usage: install.sh [OPTIONS]"
      echo ""
      echo "Install options:"
      echo "  --npm          Install via npm (installs Bun if needed)"
      echo "  --install-dir  Where to place the binary (default: ~/.local/bin)"
      echo "  --version      Version to install (default: latest)"
      echo ""
      echo "Uninstall:"
      echo "  --uninstall    Remove QraftBox and all installed files"
      exit 0
      ;;
    *) die "Unknown option: $1" ;;
  esac
done

# ----- OS / arch detection -----

detect_platform() {
  local os arch

  case "$(uname -s)" in
    Darwin) os="darwin" ;;
    Linux)  os="linux"  ;;
    *)      die "Unsupported OS: $(uname -s). QraftBox supports macOS and Linux." ;;
  esac

  case "$(uname -m)" in
    x86_64|amd64)       arch="x64"   ;;
    arm64|aarch64)       arch="arm64" ;;
    *)                   die "Unsupported architecture: $(uname -m)" ;;
  esac

  echo "${os}-${arch}"
}

# ----- Network helper -----

fetch() {
  if command -v curl &>/dev/null; then
    curl -fsSL "$@"
  elif command -v wget &>/dev/null; then
    wget -qO- "$@"
  else
    die "Neither curl nor wget found. Please install one of them."
  fi
}

download() {
  local url="$1" dest="$2"
  if command -v curl &>/dev/null; then
    curl -fsSL -o "$dest" "$url"
  elif command -v wget &>/dev/null; then
    wget -q -O "$dest" "$url"
  else
    die "Neither curl nor wget found."
  fi
}

# ----- Version resolution -----

resolve_version() {
  if [ -n "$VERSION" ]; then
    # Strip leading 'v' if present
    echo "${VERSION#v}"
    return
  fi

  info "Fetching latest version..."
  local tag
  tag=$(fetch "https://api.github.com/repos/${REPO}/releases/latest" \
        | grep '"tag_name"' | head -1 | sed 's/.*"tag_name"[[:space:]]*:[[:space:]]*"v\{0,1\}\([^"]*\)".*/\1/')

  if [ -z "$tag" ]; then
    die "Could not determine latest version. Specify --version manually."
  fi
  echo "$tag"
}

# ----- Receipt (install manifest) -----

write_receipt() {
  mkdir -p "$RECEIPT_DIR"
  cat > "$RECEIPT_FILE" <<EOF
# QraftBox install receipt -- generated by install.sh
# Do not edit manually. Used by --uninstall to clean up.
method=$1
install_dir=$2
lib_dir=$3
package_manager=$4
installed_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
  chmod 600 "$RECEIPT_FILE"
}

read_receipt_field() {
  local key="$1"
  if [ ! -f "$RECEIPT_FILE" ]; then
    echo ""
    return
  fi
  grep "^${key}=" "$RECEIPT_FILE" 2>/dev/null | head -1 | cut -d'=' -f2-
}

# ----- PATH helpers -----

ensure_in_path() {
  local dir="$1"
  case ":${PATH}:" in
    *":${dir}:"*) return 0 ;;
  esac

  warn "${dir} is not in your PATH."

  local shell_name
  shell_name="$(basename "${SHELL:-/bin/bash}")"
  local rc_file=""
  case "$shell_name" in
    bash)
      if [ -f "${HOME}/.bashrc" ]; then rc_file="${HOME}/.bashrc"
      elif [ -f "${HOME}/.bash_profile" ]; then rc_file="${HOME}/.bash_profile"
      fi
      ;;
    zsh)  rc_file="${HOME}/.zshrc" ;;
    fish) rc_file="${HOME}/.config/fish/config.fish" ;;
  esac

  if [ -n "$rc_file" ]; then
    if [ "$shell_name" = "fish" ]; then
      echo "fish_add_path ${dir}" >> "$rc_file"
    else
      echo "export PATH=\"${dir}:\$PATH\"" >> "$rc_file"
    fi
    ok "Added ${dir} to PATH in ${rc_file}"
    info "Run the following to apply now:  export PATH=\"${dir}:\$PATH\""
  else
    warn "Add the following to your shell profile manually:"
    echo "  export PATH=\"${dir}:\$PATH\""
  fi
}

# Remove the PATH line that install added to shell rc files.
# Only removes exact lines the installer would have written.
clean_path_from_rc() {
  local dir="$1"
  local shell_name
  shell_name="$(basename "${SHELL:-/bin/bash}")"

  local rc_files=()
  case "$shell_name" in
    bash) rc_files=("${HOME}/.bashrc" "${HOME}/.bash_profile") ;;
    zsh)  rc_files=("${HOME}/.zshrc") ;;
    fish) rc_files=("${HOME}/.config/fish/config.fish") ;;
  esac

  for rc_file in "${rc_files[@]}"; do
    [ -f "$rc_file" ] || continue

    local pattern
    if [ "$shell_name" = "fish" ]; then
      pattern="fish_add_path ${dir}"
    else
      pattern="export PATH=\"${dir}:\$PATH\""
    fi

    if grep -qF "$pattern" "$rc_file" 2>/dev/null; then
      # Use a temp file for portable in-place editing (macOS sed differs from GNU)
      local tmpfile
      tmpfile=$(mktemp)
      grep -vF "$pattern" "$rc_file" > "$tmpfile"
      mv "$tmpfile" "$rc_file"
      ok "Removed PATH entry from ${rc_file}"
    fi
  done
}

# ----- Install: Binary download -----

install_binary() {
  local version platform archive_name url tmpdir

  version=$(resolve_version)
  platform=$(detect_platform)
  archive_name="${BINARY_NAME}-v${version}-${platform}.tar.gz"
  url="https://github.com/${REPO}/releases/download/v${version}/${archive_name}"

  info "Installing QraftBox v${version} (${platform}) to ${INSTALL_DIR} ..."

  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  info "Downloading ${archive_name} ..."
  download "$url" "${tmpdir}/${archive_name}" \
    || die "Download failed. Check that v${version} exists at: https://github.com/${REPO}/releases"

  info "Extracting..."
  tar -xzf "${tmpdir}/${archive_name}" -C "$tmpdir"

  # The archive extracts to qraftbox-vX.X.X-os-arch/
  local extracted_dir="${tmpdir}/${BINARY_NAME}-v${version}-${platform}"
  if [ ! -d "$extracted_dir" ]; then
    # Try finding the directory
    extracted_dir=$(find "$tmpdir" -maxdepth 1 -type d -name "${BINARY_NAME}-*" | head -1)
  fi

  if [ -z "$extracted_dir" ] || [ ! -f "${extracted_dir}/${BINARY_NAME}" ]; then
    die "Unexpected archive structure. Expected ${BINARY_NAME} binary inside archive."
  fi

  mkdir -p "$INSTALL_DIR"
  cp "${extracted_dir}/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
  chmod +x "${INSTALL_DIR}/${BINARY_NAME}"

  # If the archive includes client assets, install alongside
  local lib_dir=""
  if [ -d "${extracted_dir}/dist" ]; then
    lib_dir="${INSTALL_DIR}/../lib/qraftbox"
    mkdir -p "$lib_dir"
    cp -r "${extracted_dir}/dist" "$lib_dir/"
    # Resolve to absolute path for the receipt
    lib_dir="$(cd "$lib_dir" && pwd)"
  fi

  write_receipt "binary" "$INSTALL_DIR" "$lib_dir" ""

  ok "Installed ${BINARY_NAME} to ${INSTALL_DIR}/${BINARY_NAME}"
  ensure_in_path "$INSTALL_DIR"
}

# ----- Install: npm (with Bun) -----

ensure_bun() {
  if command -v bun &>/dev/null; then
    ok "Bun is already installed: $(bun --version)"
    return 0
  fi

  info "Bun not found. Installing Bun..."
  fetch https://bun.sh/install | bash

  # Source the updated environment
  export BUN_INSTALL="${HOME}/.bun"
  export PATH="${BUN_INSTALL}/bin:${PATH}"

  if ! command -v bun &>/dev/null; then
    die "Bun installation succeeded but 'bun' is not in PATH. Please restart your shell and retry."
  fi

  ok "Bun installed: $(bun --version)"
}

install_npm() {
  ensure_bun

  local pkg_spec pkg_manager
  if [ -n "$VERSION" ]; then
    pkg_spec="qraftbox@${VERSION}"
  else
    pkg_spec="qraftbox"
  fi

  if command -v npm &>/dev/null; then
    pkg_manager="npm"
    info "Installing ${pkg_spec} via npm..."
    npm install -g "$pkg_spec"
  else
    # Bun doesn't bundle npm; install globally via bun
    pkg_manager="bun"
    warn "npm not found. Using 'bun add --global' instead."
    bun add --global "$pkg_spec"
  fi

  write_receipt "npm" "" "" "$pkg_manager"

  ok "Installed ${pkg_spec}"
}

# ----- Uninstall -----

uninstall() {
  echo ""
  printf "${BOLD}  QraftBox Uninstaller${RESET}\n"
  echo ""

  local method install_dir lib_dir pkg_manager
  local found_something=false

  # --- Read receipt if it exists ---
  method=$(read_receipt_field "method")
  install_dir=$(read_receipt_field "install_dir")
  lib_dir=$(read_receipt_field "lib_dir")
  pkg_manager=$(read_receipt_field "package_manager")

  if [ -n "$method" ]; then
    info "Found install receipt (method=${method})"
  else
    info "No install receipt found. Scanning for QraftBox installations..."
  fi

  # --- Remove binary installation ---
  # Check receipt path first, then common locations
  local binary_paths=()
  if [ -n "$install_dir" ]; then
    binary_paths+=("${install_dir}/${BINARY_NAME}")
  fi
  # Also check common locations even without receipt
  binary_paths+=(
    "${DEFAULT_INSTALL_DIR}/${BINARY_NAME}"
    "/usr/local/bin/${BINARY_NAME}"
  )
  # Check where `which` finds it
  local which_path
  which_path=$(command -v "$BINARY_NAME" 2>/dev/null || true)
  if [ -n "$which_path" ]; then
    binary_paths+=("$which_path")
  fi

  # Deduplicate and remove found binaries
  local seen_paths=""
  for bin_path in "${binary_paths[@]}"; do
    # Skip duplicates
    case " $seen_paths " in
      *" ${bin_path} "*) continue ;;
    esac
    seen_paths="$seen_paths ${bin_path}"

    if [ -f "$bin_path" ]; then
      rm -f "$bin_path"
      ok "Removed binary: ${bin_path}"
      found_something=true

      # Clean PATH entry for the directory containing this binary
      clean_path_from_rc "$(dirname "$bin_path")"
    fi
  done

  # --- Remove lib directory (client assets) ---
  local lib_dirs=()
  if [ -n "$lib_dir" ]; then
    lib_dirs+=("$lib_dir")
  fi
  lib_dirs+=(
    "${DEFAULT_INSTALL_DIR}/../lib/qraftbox"
    "/usr/local/lib/qraftbox"
  )

  local seen_libs=""
  for ld in "${lib_dirs[@]}"; do
    # Resolve to real path for dedup (ignore errors for non-existent paths)
    local resolved
    resolved="$(cd "$ld" 2>/dev/null && pwd)" || continue

    case " $seen_libs " in
      *" ${resolved} "*) continue ;;
    esac
    seen_libs="$seen_libs ${resolved}"

    if [ -d "$resolved" ]; then
      rm -rf "$resolved"
      ok "Removed lib directory: ${resolved}"
      found_something=true
    fi
  done

  # --- Remove npm/bun global package ---
  if [ "$method" = "npm" ] || [ -z "$method" ]; then
    # Try npm uninstall
    if command -v npm &>/dev/null; then
      local npm_list
      npm_list=$(npm list -g --depth=0 2>/dev/null || true)
      if echo "$npm_list" | grep -q "qraftbox@"; then
        info "Removing npm global package..."
        npm uninstall -g qraftbox
        ok "Removed npm global package: qraftbox"
        found_something=true
      fi
    fi

    # Try bun global remove
    if command -v bun &>/dev/null; then
      # bun doesn't have a clean "list globals" command; try remove and ignore errors
      if bun remove --global qraftbox 2>/dev/null; then
        ok "Removed bun global package: qraftbox"
        found_something=true
      fi
    fi
  fi

  # --- Remove receipt and config directory ---
  if [ -f "$RECEIPT_FILE" ]; then
    rm -f "$RECEIPT_FILE"
    found_something=true
  fi
  # Remove config dir only if it's empty (user may have other config)
  if [ -d "$RECEIPT_DIR" ]; then
    rmdir "$RECEIPT_DIR" 2>/dev/null || true
  fi

  # --- Summary ---
  echo ""
  if [ "$found_something" = true ]; then
    printf "${GREEN}${BOLD}  QraftBox has been uninstalled.${RESET}\n"
  else
    warn "No QraftBox installation was found."
    echo ""
    echo "  If you installed QraftBox to a custom directory, specify it:"
    echo "    install.sh --uninstall --install-dir /your/custom/path"
  fi
  echo ""
}

# ----- Main -----

main() {
  if [ "$DO_UNINSTALL" = true ]; then
    uninstall
    exit 0
  fi

  echo ""
  printf "${BOLD}  QraftBox Installer${RESET}\n"
  printf "${DIM}  All You Need Is Diff.${RESET}\n"
  echo ""

  case "$INSTALL_METHOD" in
    binary) install_binary ;;
    npm)    install_npm ;;
    *)      die "Unknown install method: $INSTALL_METHOD" ;;
  esac

  echo ""
  printf "${GREEN}${BOLD}  Installation complete!${RESET}\n"
  echo ""
  echo "  Start QraftBox:"
  echo "    $ qraftbox"
  echo ""
  echo "  Or open a specific project:"
  echo "    $ qraftbox /path/to/your/project"
  echo ""
  echo "  Uninstall:"
  echo "    $ curl -fsSL https://raw.githubusercontent.com/tacogips/QraftBox/main/install.sh | bash -s -- --uninstall"
  echo ""
  echo "  For help:"
  echo "    $ qraftbox --help"
  echo ""
}

main
