version: '3'

vars:
  PROJECT_NAME: qraftbox

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - bun install

  dev:
    desc: Run backend + client dev servers with hot reload
    deps:
      - dev:server
      - dev:client

  dev:server:
    desc: Run backend server with watch
    cmds:
      - bun run --watch src/main.ts

  dev:client:
    desc: Run Vite dev server with HMR
    dir: client
    cmds:
      - bun run dev

  build:
    desc: Build the project
    cmds:
      - bun run build

  start:
    desc: Run the application
    cmds:
      - bun run start

  test:
    desc: Run tests with Vitest
    cmds:
      - bun run test

  test-watch:
    desc: Run tests in watch mode with Vitest
    cmds:
      - bun run test:watch

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - vitest run --reporter=verbose

  test-ui:
    desc: Run tests with Vitest UI
    cmds:
      - vitest --ui

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - bun run typecheck

  fmt:
    desc: Format code with prettier
    cmds:
      - bun run format

  fmt-check:
    desc: Check code formatting
    cmds:
      - bun run format:check

  lint:
    desc: Run all lints (format check + typecheck)
    cmds:
      - task: fmt-check
      - task: typecheck

  clean:
    desc: Clean build artifacts
    cmds:
      - bun run clean

  e2e:
    desc: Run Playwright E2E tests
    cmds:
      - bunx playwright test

  e2e-ui:
    desc: Run Playwright E2E tests with UI mode
    cmds:
      - bunx playwright test --ui

  e2e-headed:
    desc: Run Playwright E2E tests in headed browser
    cmds:
      - bunx playwright test --headed

  e2e-check:
    desc: Verify Playwright browsers are installed and working
    cmds:
      - echo "PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH"
      - bunx playwright --version
      - ls "$PLAYWRIGHT_BROWSERS_PATH" 2>/dev/null || echo "Browsers not found. Run 'nix develop' first."

  ci:
    desc: Run all CI checks
    cmds:
      - task: fmt-check
      - task: typecheck
      - task: test
      - task: build
